# Generated by Django 4.0.8 on 2022-12-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'ordering': ('orcamento',)},
        ),
    ]
