# Generated by Django 4.0.8 on 2022-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_patrimonio_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_diaria',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Código'),
        ),
    ]
