# Generated by Django 4.0.8 on 2022-12-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_produto_preco_diaria_alter_produto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_compra',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço'),
        ),
    ]
