# Generated by Django 4.0.8 on 2022-12-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_remove_produto_preco_compra_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fabrica',
            field=models.CharField(blank=True, choices=[('REALCE', 'REALCE'), ('RINCAO', 'RINCAO'), ('DAF', 'DAF'), ('FORMACASA', 'FORMACASA'), ('GAZIN', 'GAZIN'), ('MV', 'MV'), ('MS DECOR', 'MS DECOR'), ('ANJOS COLCHOES', 'ANJOS COLCHOES'), ('DORIGON', 'DORIGON'), ('SALA VIPP', 'SALA VIPP'), ('ZU HOUSE', 'ZU HOUSE'), ('ARTE CUBICA', 'ARTE CUBICA'), ('CRISTALFLEX', 'CRISTALFLEX'), ('MACROSUL', 'MACROSUL'), ('MAMBEL', 'MAMBEL'), ('LED', 'LED'), ('COLOMI', 'COLOMI'), ('DARCY', 'DARCY'), ('LAFF', 'LAFF'), ('ROGAR', 'ROGAR'), ('METTA MOBILI', 'METTA MOBILI'), ('MEYER', 'MEYER'), ('SALKA', 'SALKA'), ('ELEMIS', 'ELEMIS'), ('MONTE BELO', 'MONTE BELO'), ('NIRUMA', 'NIRUMA'), ('WANG E CIA', 'WANG E CIA'), ('AVOZZANI', 'AVOZZANI'), ('PREVILEGE', 'PREVILEGE'), ('SCHNEIDER', 'SCHNEIDER'), ('VITORIA DESIGNER', 'VITORIA DESIGNER')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='madeira',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tecido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
