# Generated by Django 4.0.8 on 2022-12-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_fabrica_produto_madeira_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_cred',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço_a_Credito'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço_a_Vista'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
