# Generated by Django 4.0.8 on 2022-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0012_contrato_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='address_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='country',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='endereco_entrega',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço Entrega'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
    ]
