# Generated by Django 4.0.8 on 2022-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0013_orcamento_address_orcamento_address_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo',
            field=models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF')], default='CNPJ', max_length=4),
        ),
    ]
