# Generated by Django 4.0.8 on 2022-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0015_rename_nome_fantasia_orcamento_incricao_est'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='incricao_est',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='inscricao_est',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
