# Generated by Django 4.0.8 on 2022-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0016_remove_orcamento_incricao_est_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='frete',
            field=models.CharField(choices=[('isento', 'ISENTO'), ('cobrado', 'COBRADO'), ('retira', 'RETiRA')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='montagem',
            field=models.CharField(blank=True, choices=[('sim', 'SIM'), ('não', 'NÃO')], max_length=30, null=True),
        ),
    ]
