# Generated by Django 4.0.8 on 2022-12-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0018_orcamento_data_entrega_orcamento_freteiro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='sai_de_onde',
            field=models.CharField(blank=True, choices=[('COMERCIAL', 'COMERCIAL'), ('MANHÃ', 'MANHÃ'), ('TARDE', 'TARDE')], max_length=255, null=True, verbose_name='sai de onde'),
        ),
    ]
